### PR TITLE
Fix delayed RX with channel change

### PR DESCRIPTION
**Pull request by jciupis**
With the currently implemented logic, the core module does not notify that entering `RECEIVE` state has succeeded when state is already set to `RECEIVE`. It is misleading and causes delayed frame reception to fail, since its callback is never called. This PR fixes this and also corrects RX setup time to match logic analyzer measurements.

### CODE REVIEW

**Comment by jciupis** [comment]
Regression test

**Comment by hubertmis** [comment]
Regression test

**Comment by hubertmis** [comment]
Regression test

**Comment by hubertmis** [comment]
Regression test

**Comment by hubertmis** [comment]
Regression test

**Comment by hubertmis** [comment]
Regression test

**Pull request merged**
