### PR TITLE
[decoder] Clean up HTML alignment.

### PR DESCRIPTION
**Pull request by KaSroka**

### CODE REVIEW

**Comment by KaSroka** [comment]
Test

**Comment by KaSroka** [comment]
Bamboo build

**Comment by KaSroka** [comment]
Bamboo test

**Comment by hubertmis** [comment]
Bamboo don't test

**Comment by KaSroka** [comment]
Bamboo test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Comment by KaSroka** [comment]
Regression test

**Pull request closed without merging**
